import sys

print("CONNECT classroom.cs.unc.edu 9000")
print("CONNECT accepted for FTP server at host classroom.cs.unc.edu and port 9000")
sys.stdout.write("USER anonymous\r\n")
sys.stdout.write("PASS guest@\r\n")
sys.stdout.write("SYST\r\n")
sys.stdout.write("TYPE I\r\n")
print("GET pictures/jasleen.jpg")
print("GET accepted for pictures/jasleen.jpg")
sys.stdout.write("PORT 152,2,129,144,31,64\r\n")
sys.stdout.write("RETR pictures/jasleen.jpg\r\n")
print("GET pictures/unc.jpg")
print("GET accepted for pictures/unc.jpg")
sys.stdout.write("PORT 152,2,129,144,31,65\r\n")
sys.stdout.write("RETR pictures/unc.jpg\r\n")
print("CONNECT classroom.cs.unc.edu 21")
print("CONNECT accepted for FTP server at host classroom.cs.unc.edu and port 21")
sys.stdout.write("USER anonymous\r\n")
sys.stdout.write("PASS guest@\r\n")
sys.stdout.write("SYST\r\n")
sys.stdout.write("TYPE I\r\n")
print("GET index.html")
print("GET accepted for index.html")
sys.stdout.write("PORT 152,2,129,144,31,64\r\n")
sys.stdout.write("RETR index.html\r\n")
print("GET file\u00ff")
print("ERROR -- pathname")
print("CONNECT classroom\u00ff.cs.unc.edu")
print("ERROR -- server-host")
print("CONNECT classroom.cs.unc.edu 65536")
print("ERROR -- server-port")
print("CONNECT classroom.cs.unc.edu 090")
print("ERROR -- server-port")
print("CONNECT classroom0999.83sdkf.cs.unc.edu 90")
print("ERROR -- server-host")
print("CONNECT c 90")
print("ERROR -- server-host")
print("CONNECT edu 90")
print("CONNECT accepted for FTP server at host edu and port 90")
sys.stdout.write("USER anonymous\r\n")
sys.stdout.write("PASS guest@\r\n")
sys.stdout.write("SYST\r\n")
sys.stdout.write("TYPE I\r\n")
print("QUIT")
print("QUIT accepted, terminating FTP client")
sys.stdout.write("QUIT\r\n")

